### ISSUE TITLE
Add spring-cloud-function-stream-processor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#104]
As a developer, I'd like to add `spring-cloud-function-stream-processor` as an OOTB processor.

_Note: it'd be a port of Mark's [spring-cloud-function-stream-processor](https://github.com/markfisher/spring-cloud-function-stream-processor)._

**Acceptance:**
- Decide whether to bundle this app with all the supported binders vs. generating apps for each
- Reference guide updated with supported properties
- Tests added

**Comment by ericbottard** [comment]
See https://github.com/spring-cloud-stream-app-starters/function/pull/1
