### ISSUE TITLE
Add spring-cloud-function-stream-sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#106]
As a developer, I'd like to add `spring-cloud-function-stream-sink` as an OOTB sink.

**Acceptance:**
- Decide whether to bundle this app with all the supported binders vs. continue to generate apps for each binder
- Reference guide updated with supported properties
- App coordinate included in application metadata and aggregated http-endpoint artifacts
- Test coverage included

**Comment by markfisher** [comment]
This should probably be called `spring-cloud-function-stream-sink` (consistent with `spring-cloud-function-stream-processor` where the last term is aligned with the role it plays within SCDF).

**Comment by ericbottard** [comment]
See https://github.com/spring-cloud-stream-app-starters/function/pull/1
