### ISSUE TITLE
Misleading default values for log-level in app docs

### ISSUE THREAD

**Issue by trisberg** [spring-cloud-stream-app-starters/app-starters-release#108]
Several properties indicate <none> as a default while the property actually has a default or generates a value. We should improve this.

A couple of examples:

1) log sink has the following:

log.level
    The level at which to log messages. (Level, default: <none>, possible values: FATAL,ERROR,WARN,INFO,DEBUG,TRACE)

If I leave that property out I get `INFO` which seems to be the de-facto default.

2) http source has this:

server.port
    Server HTTP port. (Integer, default: <none>)

Leaving that out results in port set to 8080 or even a generated random port, depending on platform.

**Comment by sabbyanandan** [comment]
This cannot be addressed OOTB.
