### ISSUE TITLE
Update Spring Boot, Spring Cloud, and SCSt to "Edgware" release train

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#110]
As a developer, I'd like to create a new branch/CI to generate apps based on Edgware release-train.

**Comment by sobychacko** [comment]
This issue is resolved via https://github.com/spring-cloud-stream-app-starters/core/commit/085910a55dbb6cfd1464543e9b0de5f87a60c860
