### ISSUE TITLE
Consider converting generated metadata to simple names

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#119]
As discussed in [spring-cloud-stream-app-starters/app-starters-release#99](https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/99#issuecomment-313502025), we would like to convert the listing of supported properties as simpler names.

> Can we also change the metadata generator so that it provides simple names, such as "string, boolean, comma-delimited strings" instead of <java.lang.String>, <java.lang.Boolean>, <java.util.List<java.lang.String>>?

**Comment by sabbyanandan** [comment]
@ericbottard: Do you have any ideas?

**Comment by ericbottard** [comment]
Commented on the original issue, starting work on it

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-app-starters-maven-plugins/commit/047d05a14b955d2d49ac140d4a58ab17838fc195
