### ISSUE TITLE
Add a generic description for handling byte[] payloads in SpEL and Groovy expressions. 

### ISSUE THREAD

**Issue by tzolov** [spring-cloud-stream-app-starters/app-starters-release#166]
Starting with SCSt 2.x the payload's wire format for `text`, `json`, `xml` and alike content-type has changed from `string` to `byte[]`.  This change requires a special handling in SpEL expressions and and Groovy scripts.  For example the old `payload.contains('a')` expression won't work anymore. The workaround is to convert the payload into string like this: `new String(payload).contains('a')`.
At the same time expressions that use xpath() or jsonPath() utilities would not be affected as the later handle byte[] and string interchangeably.  For other types a special conversion beans can be used (ref: @artembilan ). 
Therefore we need to create a adoc fragment explaining those changes that we can include in all affected app starters such as `router`, `splitter` and alike. 

Related to https://github.com/spring-cloud-stream-app-starters/router/pull/3

**Comment by sabbyanandan** [comment]
- [ ] Router
- [ ] Splitter

**Comment by markpollack** [comment]
Shouldn't the specification of content type on the input be the preferred way instead of using `new String(payload)`.  It does seem a bit odd to have to do that now.  Perhaps there are other approaches with default content types that would look cleaner.

**Comment by artembilan** [comment]
This issue may be related: https://github.com/spring-cloud-stream-app-starters/transform/issues/6

**Comment by sabbyanandan** [comment]
We have addressed this problem in SCSt Elmhurst.SR2 and as well in all the associated Apps via Darwin.SR3 release. We do not need any special documentation on this subject anymore.
