### ISSUE TITLE
Fix failing CI tests

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#168]
- [x] Aggregate - @artembilan 
- [x] AWS - @artembilan 
- [x] Groovy Filter (fixed in SI)
- [x] Groovy Transform (fixed in SI)
- [x] HDFS - @jvalkeal
- [x] HTTPClient  - @artembilan 
- [x] JMS - @artembilan  
- [x] Loggregator - @sobychacko 
- [x] MongoDB - @artembilan 
- [x] Python- @dturanski 
- [x] Router - @tzolov  (fixed in SI) - groovy-all related
- [x] Scriptable Transform  (fixed in SI)
- [x] Splitter - @artembilan (fixed in SI: https://jira.spring.io/browse/INT-4556)
- [x] Twitter - @tzolov 

More details here: https://jenkins.spring.io/view/SpringScstAppStarters/view/Master-CI/

**Comment by artembilan** [comment]
I'm done with my tasks. All the Groovy-based app starters (including Scriptable Transform) are going to be fixed after the next Spring Boot release this Thursday.

If anyone need help with their task, I'm open.
