### ISSUE TITLE
Missing spring-cloud-starter-stream-sink-cassandra update in Einstein.M1 Pre-release of Spring Cloud Stream App Starters

### ISSUE THREAD

**Issue by tekeny** [spring-cloud-stream-app-starters/app-starters-release#171]
Is it unmaintained since verion 1.3.1.RELEASE?
https://github.com/spring-cloud-stream-app-starters/app-starters-release/releases/tag/vEinstein.M1

Is a release planned soon?

https://stackoverflow.com/q/53953363

**Comment by sabbyanandan** [comment]
Hi, @dk0de. We have prepared for the 2.0 release but at the time of Darwin/2.0 release-train release, the dependent artifacts weren't ready for primetime, so the app didn't make it on the train. We will revisit it for the Einstein release-train release. Thank you for bringing it up.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/cassandra#10
