### ISSUE TITLE
Rename "spring-configuration-metadata-whitelist.properties" to "dataflow-configuration-metadata-whitelist.properties"

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#174]
As a developer, I'd like to add `dataflow-configuration-metadata-whitelist.properties` in 2.1 release-train (that would be done on all the apps individually), so it would be consistent to work with SCDF 2.0's default file-name expectations. Also, we will continue to retain  `spring-configuration-metadata-whitelist.properties` (but deprecate it) for backward compatibility. 

The old file-name would continue to work as well since there'll be a fallback mechanism in place for it in SCDF via https://github.com/spring-cloud/spring-cloud-dataflow/issues/1157#issuecomment-452713423

**Comment by sobychacko** [comment]
`spring-configuration-metadata-whitelist.properties` files in all the app starter repositories are now copied to `dataflow-configuration-metadata-whitelist.properties` in the `src/main/resources/META-INF` directory.
