### ISSUE TITLE
Fix failing CI tests on Tensorflow and PMML 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#229]
Only HTTPs traffic is allowed in the Jenkins box, so we would have to not rely on the models served from the HTTP.

- [x] PMML procesor
- [x] Tensorflow core

**Comment by tzolov** [comment]
Resolved with the https://github.com/spring-cloud-stream-app-starters/pmml/commit/75f1b5cf2b418f479569de781e4622e4ee08076e and https://github.com/spring-cloud-stream-app-starters/tensorflow/commit/5f23dda5590926a3e33e68eb18e1ff91ff2038d9 commits.
