### ISSUE TITLE
Update Cassandra sink with Spring Data Cassandra version that fixes SchemaAction

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#23]
_From @sabbyanandan on May 6, 2016 17:7_

_From @trisberg on December 4, 2015 15:1_

See https://jira.spring.io/browse/DATACASS-241

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#118_

_Copied from original issue: spring-cloud/spring-cloud-stream-app-starters#63_

**Comment by artembilan** [comment]
Looks like https://jira.spring.io/browse/DATACASS-241 has been fixed and we now use `Spring Data Cassandra 1.4.3` as a transitive dependency from Boot 1.4.x.

Closing with that fact.
Feel free to open a new issue in the appropriate project if there is still need to do anything on the matter!
