### ISSUE TITLE
Generate apps for JDBC Supplier and Rabbit Consumer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#231]
Let's do it for `jdbc-source` and `rabbit-sink`.

**Acceptance:**
- [x] Adjust plugin to consume java-functions directly
- [x] Generate apps for Kafka and Rabbit
- [x] Test the apps standalone using the TestBinder

**Comment by sobychacko** [comment]
This task is complete.
