### ISSUE TITLE
Add Wavefront meter-registry to all the supported applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#251]
As we continue the core efforts on the backend/UI (see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3937), we need to prepare the OOTB applications with the Wavefront registry in the classpath, so when the apps are deployed by SCDF, all the metadata injection happens automatically.

**Comment by tzolov** [comment]
Resolved by https://github.com/spring-cloud-stream-app-starters/core/commit/facb6fe724fe04ac4df01fb397ca9212b7120ebc
