### ISSUE TITLE
Track the progress of the GA release for Avogadro

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud-stream-app-starters/app-starters-release#26]
Following artifacts/apps need to be released. 

- [x] spring-cloud-stream-app-maven-plugin - 1.2.2.RELEASE
- [x] spring-cloud-app-starter-doc-maven-plugin - 1.1.3.RELEASE
- [x] app starters core - 1.1.1.RELEASE
- [x] file  - 1.1.1.RELEASE
- [x] http  - 1.1.1.RELEASE
- [x] jdbc  - 1.1.1.RELEASE
- [x] jms  - 1.1.1.RELEASE
- [x] rabbit  - 1.1.1.RELEASE
- [x] s3  - 1.1.1.RELEASE
- [x] time - 1.1.1.RELEASE
- [x] bridge - 1.1.1.RELEASE
- [x] splitter - 1.1.1.RELEASE
- [x] file - 1.1.1.RELEASE
- [x] jdbc - 1.1.1.RELEASE
- [x] log - 1.1.1.RELEASE
- [x] rabbit - 1.1.1..RELEASE
- [x] router - 1.1.1..RELEASE
- [x] s3 - 1.1.1.RELEASE
- [x] throughput - 1.1.1.RELEASE
- [x] syslog   - 1.1.1.RELEASE
- [x] filter - 1.1.1.RELEASE
- [x] aggregate-counter - 1.1.1.RELEASE
- [x] counter - 1.1.1.RELEASE
- [x] field-value-counter - 1.1.1.RELEASE
- [x] mail - 1.1.1.RELEASE
- [x] mongodb - 1.1.1.RELEASE
- [x] httpclient - 1.1.1.RELEASE
- [x] gemfire  - 1.1.1.RELEASE
- [x] gemfire-cq - 1.1.1.RELEASE 
- [x] hdfs - 1.1.1.RELEASE
- [x] hdfs-dataset - 1.1.1.RELEASE
- [x] gpfdist - 1.1.1.RELEASE
- [x] gemfire - 1.1.1.RELEASE
- [x] sftp - 1.1.1.RELEASE  
- [x] tcp   - 1.1.1.RELEASE
- [x] tcp-client    - 1.1.1.RELEASE
- [x] tcp-client - 1.1.1.RELEASE
- [x] ftp - 1.1.1.RELEASE
- [x] tcp - 1.1.1.RELEASE
- [x] sftp - 1.1.1.RELEASE
- [x] load-generator - 1.1.1.RELEASE
- [x] loggregator - 1.1.1.RELEASE  
- [x] trigger   - 1.1.1.RELEASE
- [x] triggertask  - 1.1.1.RELEASE
- [x] twitterstream  - 1.1.1.RELEASE
- [x] groovy-filter - 1.1.1.RELEASE
- [x] groovy-transform - 1.1.1.RELEASE
- [x] pmml - 1.1.1.RELEASE
- [x] scriptable-transform - 1.1.1.RELEASE
- [x] redis-pubsub - 1.1.1.RELEASE
- [x] task-launcher-local - 1.1.1.RELEASE
- [x] task-launcher-yarn - 1.1.1.RELEASE
- [x] tasklaunchrequest-transform - 1.1.1.RELEASE
- [x] websocket - 1.1.1.RELEASE
- [x] cassandra - 1.1.1.RELEASE
- [x] app starters release - Avogadro.RELEASE

**Comment by sobychacko** [comment]
Acceptance: All the GA release artifacts are available through 
`http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/`
and 
`https://repo1.maven.org/maven2/org/springframework/cloud/stream/app/` (maven central)
and
`https://hub.docker.com/u/springcloudstream/`

**Comment by sabbyanandan** [comment]
This is complete with https://github.com/spring-cloud-stream-app-starters/app-starters-release/commit/db52f3907eea7199cf9baf0e06312e64277aa72a.
