### ISSUE TITLE
Create ZIP artifact with application metadata and whitelisted properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#47]
As a developer, I'd like to create a JAR artifact for each stream app-starter, so I embed the application metadata and the whitelisted properties in it. 

**Acceptance:**
- the JAR artifact is automatically generated at the build time
- the companion artifact can be used by other clients such as SCDF's shell, dsl and UI
- unit-tests verify the creation and existence of the companion artifact for each stream app-starter

**Comment by sobychacko** [comment]
This issue is resolved through https://github.com/spring-cloud-stream-app-starters/app-starters-release/pull/64 and https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/63. 

Also, see this PR: https://github.com/spring-cloud-stream-app-starters/core/pull/12
