### ISSUE TITLE
Add postgresql-copy sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#51]
As a developer, I'd like to add an OOTB `postgresql-copy` sink application that is built using PostgresSQL's [CopyManager](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html) Java API, so we could ingest large volumes of data more efficiently. 

**Acceptance:**
- a new repo created
- new repo hosts the `postgresql-copy` sink application and its docs
- configurable properties are documented
- sink docs are embedded in the aggregated reference guide
- sink added to the static descriptor file for bulk imports
- performance comparison between `jdbc` and `postgresql-copy` is documented

**Comment by mwright-pivotal** [comment]
Postgres COPY supports a few options that would be useful as part of this sink:
1. DELIMITER
2. CSV

Note: Passing escaped values for delimiter may require translation from a stream definition.  ie  '\t' should result in DELIMITER E'\t' on the SQL statement
