### ISSUE TITLE
Upgrade to SCSt Chelsea M1

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#53]

**Comment by sobychacko** [comment]
This will be done by upgrading `spring-cloud-dependencies` to Dalston.M1

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud-stream-app-starters/core/commit/136aa49fbe27797007e0d1fe7b6254580aa73152
