### ISSUE TITLE
http source should not have the port that is to be posted to secured by default

### ISSUE THREAD

**Issue by markpollack** [spring-cloud-stream-app-starters/app-starters-release#56]
Review how we secured all the apps to prevent actuator endpoints being exposed.  ATM, we have to present basic security creds in order to post to the endpoint. That is inconvenient ATM as the shell doesn't support http posts with basic security and http | log is a common 'first try' stream app for new users - we have it in our getting started guides.

**Comment by sobychacko** [comment]
@markpollack how about we secure all the actuator endpoints in all the apps using the `/management` context-path and only secure URL's under `/management/*`? This way normal http post from the shell won't have security enabled.

**Comment by sobychacko** [comment]
Actuator endpoints are now accessed through ` /management/*` from 1.1.2.RELEASE of http source apps onward.
