### ISSUE TITLE
Adding spring-cloud-config-server-client to OOTB apps deployed on PCF

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud-stream-app-starters/app-starters-release#80]
The goal with this is that the ootb apps can use the config server that is part of the spring cloud services tile on PCF.  Now, users would have to create their own version of the app and add this config client jar themselves.  

Acceptance: We will need to verify this on PCF and make sure that this change doesn't have any ill effect on non-PCF environments.

**Comment by mminella** [comment]
Stupid question: What is the license we release the SCS client jar under?

**Comment by sobychacko** [comment]
@mminella here is the license: https://github.com/pivotal-cf/spring-cloud-services-starters#license
