### ISSUE TITLE
TaskLauncher local docs improvements.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud-stream-app-starters/app-starters-release#88]
The readme references how it can be used in data flow, which is not appropriate to put in the docs for app starters which do not depend on using SCDF.  There should be a link to the TaskLaunchRequest javadoc and also to the docs/readme for trigger task.

There is no reference to any `@ConfigurationProperties` that are available, e.g. how would one know to set `--maven.remote-repositories.repo1.url`?

If one want to show it in action, using `java -jar` based examples is appropriate.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/tasklauncher-local#1
