### ISSUE TITLE
Add Twitter-Sentiment TensorFlow processor

### ISSUE THREAD

**Issue by tzolov** [spring-cloud-stream-app-starters/app-starters-release#90]
As a user, I'd like to have a Twitter-Sentiment TensorFlow processor that evaluates a twitter message sentiments in real-time.

Acceptance:

Twitter-Sentiment processor is hosted in a new GH repo (`tensorflow` sub-project)
CI infrastructure setup for the new processor
Uber-jar's are produced for each binder variant
Static build descriptor file includes the new processor
Samples included in the docs/README
Docs included in the aggregated reference guide

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-cloud-stream-app-starters/app-starters-release/commit/99f3134c25936a190a3c4cb477ab98d6cbb55202
