### ISSUE TITLE
Wrong JAR reference for sink.field-value-counter

### ISSUE THREAD

**Issue by adersberger** [spring-cloud-stream-app-starters/app-starters-release#93]
Within 
http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Bacon.RELEASE/spring-cloud-stream-app-descriptor-Bacon.RELEASE.kafka-10-apps-maven-repo-url.properties
the value sink.field-value-counter points to a wrong JAR URL
http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/field-value-counter-sink-kafka-10/1.2.0.libs-libs-release/field-value-counter-sink-kafka-10-1.2.0.RELEASE.jar

The part "1.2.0.libs-libs-release" is wrong an should be "1.2.0.RELEASE".

**Comment by sabbyanandan** [comment]
Hi, @adersberger: Thanks for reporting this! We will get it fixed. 😄

**Comment by sobychacko** [comment]
@adersberger This issue is resolved.
